spring:
  application:
    name: courier
  datasource:
    url: jdbc:postgresql://localhost:5436/courierdb
    password: postgres
    username: postgres
  cloud:
    function:
      definition: shipmentCreated;updateShipment;warehouseNotified;notifyWarehouse;
    config:
      enable: true
    stream:
      kafka:
        default:
          producer.configuration.key.serializer: org.apache.kafka.common.serialization.StringSerializer
          consumer:
            enableDlq: false
            autoCommitOnError: true
            autoCommitOffset: true
        binder:
          brokers: localhost:9092
          minPartitionCount: 4
          autoAddPartitions: true
          consumerProperties:
            enable.auto.commit: true
            fetch.max.bytes: 62194560
            session.timeout.ms: 15000
          producerProperties:
            retries: 3
            batch.size: 16384
            buffer.memory: 33554432
            linger.ms: 1
      bindings:
        shipmentCreated-in-0:
          destination: workflow-courier-assign-request
          content-type: application/json
          group: courier-group
        updateShipment-out-0:
          destination: workflow-courier-assign-response
          content-type: application/json
        notifyWarehouse-in-0:
          destination: workflow-courier-notify-warehouse-request
          content-type: application/json
          group: courier-group
        warehouseNotified-out-0:
          destination: workflow-courier-notify-warehouse-response
          content-type: application/json
http.client.warehouse.url: localhost:8087/api/v1/warehouse-management-system